name: MES DevOps CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Obtener codigo
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Instalar dependencias
        working-directory: ./backend
        run: npm ci

      - name: Ejecutar pruebas unitarias
        working-directory: ./backend
        run: npm test
        
- name: Agregar Docker al PATH
  shell: powershell
  run: |
    "C:\Users\alexc\AppData\Local\Programs\DockerDesktop\resources\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8

- name: Verificar Docker
  shell: powershell
  run: docker version

      - name: Construir imagen Docker
        run: docker build -t mes-devops .